### ISSUE TITLE
[Feature Request] Add config option to disable dart formatting

### ISSUE THREAD

**Issue by aroemen** [oppahansi/better_imports#3]
The dart formatter has numerous issues with allowing for customizations and is often disabled. This plugin forces the use of Dart Formatting.

**Comment by oppahansi** [comment]
I see, I have not considered that ppl have it turned off.
Will try to add the option in the next days.

**Comment by oppahansi** [comment]
You should be able to disable dart fmt now.
Open a new issue in case something is broken now ^^
